### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by need4swede** [aleksasiriski/autoscan#9]
So I have autoscan running on macOS. The media directory is on macOS (same machine).
My Jellyfin server is on Windows. It accesses the media directory via a network share (mapped to B:\).

My config looks like this:
```
targets:
  jellyfin:
    - url: http://192.168.0.109:8096
      token: xxx
      rewrite:
        - from: /Volumes/Bifrost/Yggdrasil/
          to:  B:\Yggdrasil\ 
```

I kept getting that dreaded "failed determining library" error, so I found your fork of autoscan and was hoping it would fix it.

```
No target libraries found error="B:\\Yggdrasil\\Shows/DuckTales (1987)/Season 1: failed determining library" target=jellyfin url=http://192.168.0.109:8096
```

I tried using it this way:
```
targets:
  jellyfin:
    - url: http://192.168.0.109:8096
      token: xxx
      slash-direction: "backward"
      rewrite:
        - from: /Volumes/Bifrost/Yggdrasil/
          to:  B:\Yggdrasil\
```

But that didn't do anything. Am I doing something wrong?
I've even tried using symbolic links, ie `C:\Bifrost\Yggdrasil\` but I still run into the same issue with `\` and `/`.

Thanks!
